#!/usr/bin/env python

import xmlrpc.client
import sys

# getfreq is a python program to use xmlrpc to FLRig
# if you have cat control for FLRig then this will work
# for you.

try:    
    # Connect to the flrig server on localhost port 12345
    server_url = "http://localhost:12345"
    flrig = xmlrpc.client.ServerProxy(server_url)
    version = flrig.main.get_version
    print("Connected to flrig version:",version())

    rfreq = flrig.rig.get_vfo()

    freq = str(rfreq)
    print(f" {freq} ")
except ConnectionRefusedError: 
    print("CONNECT-ERROR\n")
